name: Run Artillery Tests on PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out main repository
        uses: actions/checkout@v2

      - name: Clone Artillery Repository
        run: |
          git clone https://github.com/cedricongjh/test-artillery-repo.git
          mkdir -p ./artillery-repo  # Create the directory if it doesn't exist
        working-directory: .

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Artillery
        run: npm install -g artillery

      - name: Run Artillery Tests
        run: |
          cd ./artillery-repo
          artillery run home-load-test.yml
